### ISSUE TITLE
Sign Up (Thrs April 23rd)

### ISSUE THREAD

**Issue by PureKrome** [OpenHackOrg/Melbourne.AU#6]
Time: 6:00pm - 8:00/8:30pm

Space: [Discovery Centre Seminar Room](http://museumvictoria.com.au/melbournemuseum/discoverycentre/visit-our-onsite-centre/) at Melbourne Museum
Address: [Lower Ground, Melbourne Museum, Carlton Gardens](https://www.google.com.au/maps/place/Melbourne+Museum/@-37.803646,144.972942,17z/data=!3m1!4b1!4m15!1m12!4m11!1m3!2m2!1d144.9735214!2d-37.8034383!1m6!1m2!1s0x6ad642da40c9de9f:0x8f2c10c1546cc221!2sMelbourne+Museum,+11+Nicholson+St,+Carlton+VIC+3053,+Australia!2m2!1d144.972942!2d-37.803646!3m1!1s0x6ad642da40c9de9f:0x8f2c10c1546cc221?hl=en)

---

Special mention(s)
1. Massive shoutout to @michael-mason for booking this at the Museum.
2. Melbourne Museum for offering bookings :+1:

**Comment by PureKrome** [comment]
In! Can't wait :+1:

**Comment by frankradocaj** [comment]
+1

**Comment by PureKrome** [comment]
@frankradocaj - date changed.... is that still ok for you?

**Comment by frankradocaj** [comment]
Yep, all good.

**Comment by DavidBurela** [comment]
Sure. Count me in.
~~FYI: On the info page http://openhack.github.io/melbourne/ the _(Please sign up @ our GitHub repo)_ link goes to the old signup page~~ I created a pull request to update it.

**Comment by RPM1984** [comment]
+1

**Comment by mottey** [comment]
+1
React Native tinkering this time...

**Comment by michael-mason** [comment]
:+1:

**Comment by willl** [comment]
A +1.

**Comment by ssherrin** [comment]
+1

**Comment by PureKrome** [comment]
Rough Instructions for tonight (via @michael-mason on JabbR)..
- Go through the main entrance to the MM.
- Maybe have to sign in? (we're not sure)
- There's a guard there. Ask him where to go.
  ...
  ..
  .. and he/she will say:
- Turn left
- Go down the escalators.
- :moneybag: :moneybag: :moneybag:

**Comment by michael-mason** [comment]
so more details on whats happening.
- no security guards on the door tonight, so it will just be me greeting you and pointing you in the right direction as you arrive.
- you will have to sign in and wear a visitors lanyard.
- there will be snacks provided by the very gracious Simon Sherrin.

**Comment by PureKrome** [comment]
@ssherrin 

![](http://i.giphy.com/vCKC987OpQAco.gif)

**Comment by michael-mason** [comment]
They remind me of two rutting caterpillars fighting for the affections of a lady caterpillar.

**Comment by PureKrome** [comment]
:shipit: 

Thanks _heaps_ for everyone that came tonight, for @michael-mason and @ssherrin for setting up _and_ for the food. Really appreciated it!

**Comment by DavidBurela** [comment]
Last night I mentioned Xamarin.Forms here are some links:
Xamarin.Forms website http://xamarin.com/forms

And this is the webinar I did on how to do Xamarin.Forms with MVVM (ViewModels, databinding, etc.) https://www.youtube.com/watch?v=sbFl47NM5fo

![](http://xamarin.com/content/images/pages/forms/example-app.png)
